This happens when you got a password with ‘@’, which may cause some problems with the connection string. 
Try this: 

  from urllib.parse import quote_plus
  password = 'mysq@123'
  encoded_password = quote_plus(password)
  app.config['SQLALCHEMY_DATABASE_URI'] = f'mysql://root:{encoded_password}@localhost'
